export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ID!;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGE_BUCKET_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT!;
export const PROJECTS_ID =
	process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID ??
	process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID ??
	"";
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;